owner: corentin-verquin
repo: status
user-agent: koj-co
sites: # List of endpoints to track
  - name: corentin-verquin
    url: https://corentin-verquin.fr/
  - name: ply-reader
    url: https://demo-ply.corentin-verquin.fr/
  - name: dockernet
    url: https://demo-dockernet.corentin-verquin.fr/
assignees: # Users to assign downtime issues (optional)
  - corentin-verquin
status-website:  
  baseUrl: /status
  name: Upptime
