owner: corentin-verquin
repo: status
user-agent: koj-co
sites: # List of endpoints to track
  - name: CV
    url: https://corentin-verquin.fr/
assignees: # Users to assign downtime issues (optional)
  - corentin-verquin
